version: "3.0"

services:
#  drf:
#    build: ./RestAPIProject
#    container_name: drf
#    command: gunicorn --bind 0.0.0.0:8000 RestAPIProject.wsgi
#    volumes:
#      - ./RestAPIProject:/app
#      - static_volume:/app/static
#      - media_volume:/app/media
#    ports:
#      - "8000:8000"
#    env_file:
#      - ./RestAPIProject/.env
#    depends_on:
#      - db
#      - redis
#      - celery
  fast:
    build: ./WebSocketChatProject
    container_name: fast
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./WebSocketChatProject:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: 'chat_db'
      POSTGRES_USER: 'chat_admin'
      POSTGRES_PASSWORD: 'chat_admin'
      POSTGRES_HOST: 'db'
      POSTGRES_PORT: 5432
#  redis:
#    image: redis:6-alpine
#    volumes:
#      - redis_data:/data/
#    expose:
#      - 6379
#  celery:
#    build: ./RestAPIProject
#    command: celery -A RestAPIProject worker --loglevel=info
#    volumes:
#      - ./RestAPIProject:/app
#    depends_on:
#      - redis
#  nginx:
#    build: ./nginx
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"
#    volumes:
#      - static_volume:/app/static
#      - media_volume:/app/media
#    ports:
#      - "80:80"
#    depends_on:
#      - drf

volumes:
  static_volume:
  media_volume:
#  redis_data: