"""Email added to UserData model

Revision ID: b5afaa120d1a
Revises: 94f25caf7780
Create Date: 2024-01-19 17:30:35.953508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5afaa120d1a'
down_revision: Union[str, None] = '94f25caf7780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'email')
    # ### end Alembic commands ###
